#!/bin/bash
rm -rf /etc/xray/config.json
rm -rf /etc/nginx/conf.d/xray.conf
wget -q -O /etc/nginx/conf.d/xray.conf "https://raw.githubusercontent.com/Jatimpark/opok/main/config/xray.conf"
wget -q -O /etc/xray/config.json "https://raw.githubusercontent.com/Jatimpark/aman/main/opok/config.json"
systemctl restart nginx xray
m-vm.f
